### ISSUE TITLE
Feature: customize/disable animation

### ISSUE THREAD

**Issue by Misiu** [material-extended/mde#14]
#### Bug, feature request, or proposal:
Hi,
I'd like to ask for a way to customize/disable animation for show/hide. Currently they are hardcoded.

#### What is the expected behaviour?
Add ability to customize/disable animations.

#### What is the current behaviour?
No way to customize/disable animation

**Comment by joejordanbrown** [comment]
@Misiu 

Thanks for the feature request.

**Custom Animations**
I'm still unsure if this is possible with the current `@angular/animations`, I would need to investigate the custom animations. If you find any information regarding custom animations for libs please share.

**Disable Animations**
I will look at adding this very soon.

**Comment by Misiu** [comment]
@joejordanbrown I think that disabling could be done using `@.disabled` as shown here: https://stackoverflow.com/questions/43745877/disable-animation-in-angular-2-material
but I wasn't able to do that. Maybe You can look at this?
