### ISSUE TITLE
angular 5 support

### ISSUE THREAD

**Issue by Plondrein** [material-extended/mde#15]
As it is out, can we expect support for latest  angular version ? :)

**Comment by joejordanbrown** [comment]
@Plondrein 

Yes, I've been away recently so not had time to keep up with this. I'll get that published this week, sorry for the delay.

**Comment by joejordanbrown** [comment]
@Plondrein 

That has now been published to support the latest Angular and CDK.

**Comment by Plondrein** [comment]
That's cool to hear! Thanks!
