### ISSUE TITLE
Feature request : option to remove all card decoration

### ISSUE THREAD

**Issue by jpmous** [material-extended/mde#17]
#### feature request :
I'd like to use popover to display an image only, without any decoration : no arrow, transparent background and no elevation.

#### What is the current behaviour?
I could removed the arrow setting width to zero and I could make background transparent but I have not found a way to suppress elevation of the card.

#### Other Comments
Great component for my others usage ! Thanks.

**Comment by joejordanbrown** [comment]
@jpmous 

You don't need to use the card that was just for example purposes. By default the popover has no styles.

```html
<mde-popover>
    Your HTML or Content here
</mde-popover>
```

**Comment by jpmous** [comment]
How I feel stupid ! I was happy to find a popover displaying a card that I kept on copy/paste code, not paying attention...
