### ISSUE TITLE
Compatible with IE

### ISSUE THREAD

**Issue by ridj87** [material-extended/mde#18]
#### Bug, feature request, or proposal:
Compatible with IE

#### What is the expected behaviour?
To work in IE

#### What is the current behaviour?
Not functioning in IE

#### What are the steps to reproduce?
Open in IE

Provide a working example using StackBlitz (or similar) to reproduce the problem.
StackBlitz Template: https://stackblitz.com/fork/mde-popover

#### What is the use-case or motivation for changing an existing behaviour?
Support for multiple browsers

#### Other Comments
The demo page is also not working in IE.

**Comment by joejordanbrown** [comment]
@ridj87 

I'm normally against supporting old browsers, but I'm guessing you have requirements that need to support such an old browser?

I will look into adding the polyfills to support this.

**Comment by joejordanbrown** [comment]
@ridj87 

I've checked and the library does work with I.E 11 I've updated the demo to include polyfills so that now works https://uixd.co.uk/open-source-software/material-extended/demo/ let me know if you have any problems testing it.

Thanks, appreciate it 👍

**Comment by ridj87** [comment]
I tried making an example for you to check out:
https://stackblitz.com/edit/mde-popover-w3buka?file=app%2Fapp.component.html

it's the basic template but with hover instead. I can't get it to work in IE so that was little help.
I still can't get it to work in my client. I get no error messages but nothing pops up in IE.
Here is my setup for the application:

    "@angular/animations": "^5.0.1",
    "@angular/cdk": "^5.0.0-rc0",
    "@angular/common": "^5.0.1",
    "@angular/compiler": "^5.0.1",
    "@angular/core": "^5.0.1",
    "@angular/flex-layout": "git+https://github.com/angular/flex-layout-builds.git",
    "@angular/forms": "^5.0.1",
    "@angular/http": "^5.0.1",
    "@angular/material": "^5.0.0-rc0",
    "@angular/platform-browser": "^5.0.1",
    "@angular/platform-browser-dynamic": "^5.0.1",
    "@angular/router": "^5.0.1",
    "@material-extended/mde": "^1.0.0-alpha.6",
    "@swimlane/ngx-datatable": "^11.0.4",
    "@types/moment": "^2.13.0",
    "angular2-hotkeys": "^2.0.3",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.4.1",
    "hammerjs": "^2.0.8",
    "intl": "^1.2.5",
    "moment": "^2.18.1",
    "ngx-progressbar": "^2.0.8",
    "rxjs": "^5.1.0",
    "web-animations-js": "^2.3.1",
    "zone.js": "^0.8.4"

**Comment by ridj87** [comment]
@joejordanbrown I have tried to create a simple popover in my client now and it works, the problem seems related to me trying to add a popover to a button, inside a grid. I will investigate further what is causing the issue.

**Comment by ridj87** [comment]
@joejordanbrown it was actually the <mat-icon> that I had put the logic for the popover on that was causing the issue in IE. I moved popover triggerOn and triggerfor  to the button outside of it and now it works in IE.
