### ISSUE TITLE
Metadata version mismatch for module

### ISSUE THREAD

**Issue by kamok** [material-extended/mde#19]
#### Bug, feature request, or proposal:
After updating to the latest alpha, I'm getting this error.
It seems like it can be fixed using this:
https://github.com/angular/material2/issues/8229#issuecomment-342502556

Which basically says upgrade EVERYTHING in angular and angular material to 5 RC0. 
I do NOT want to do that. Is this intended? 

#### What are the steps to reproduce?

Provide a working example using StackBlitz (or similar) to reproduce the problem.
StackBlitz Template: https://stackblitz.com/fork/mde-popover

**Comment by kamok** [comment]
I'm isolating it to this specific package. I can get around it by simply removing the imports from `app.modules` for the package, let it compile. Then of course it errors out because I'm using binding in the html from this package. So I let the imports back in. And it works. 

However, my tests are showing that error.

**Comment by kamok** [comment]
Ok I didn't know that 1.05 was depending on Angular 5 as well. I reverted all the way back to 1.04.

**Comment by joejordanbrown** [comment]
@kamok 

It requires Angular 5 now to use the latest version. Is there a reason you can't upgrade your project to Angular 5?

**Comment by kamok** [comment]
@joejordanbrown 
Since I'm working on a team, I'll have to make everyone else fix any breaking changes induced by Angular 5. Here's the changes https://jaxenter.com/road-to-angular-5-133253.html

Which is not a priority if the product has a deadline. Do you have changelog from 1.04 to 1.06? After reverting, something doesn't seem right with the dynamic positioning you did for me in the other post.

**Comment by joejordanbrown** [comment]
@kamok 

That's fair enough, I've found that as long as you are not using a lot of the deprecated APIs in the current app, upgrading has been pretty smooth. 

I noticed that the automated changelog hasn't been receiving all the commit messages. I need to remember to follow appropriate commit messages for that to work.

#### You can see the changes [here](https://github.com/material-extended/mde/compare/v1.0.0-alpha.4...v1.0.0-alpha.6).

Here is a list of changes to the library between the releases `1.04` to `1.06`.
- Upgrade Angular peerDependencies from `>=4.0.0 <5.0.0` to `>=5.0.0 <6.0.0`.
- Upgrade CDK peerDependencies from `^2.0.0-beta.11` to `^5.0.0-rc0`.
- Upgrade devDependencies.
- Rename MdePopoverTrigger `_element` to `_elementRef`.
- Change MdePopoverTrigger `_elementRef` from `private` to `public`.
