### ISSUE TITLE
Multiple popovers appear with delay

### ISSUE THREAD

**Issue by kdudzik** [material-extended/mde#2]
I'm trying to use MDE popovers as presented here:
http://plnkr.co/edit/ebs4IqbYGq5sRRj7AuKD?p=preview

I've created custom components for the trigger and one to attach a popover to the trigger using `<ng-content>`. I've set a delay of 1000ms for showing the popover.

Now, when hovering quickly over multiple triggers, multiple popovers appear with a 1000ms delay. Only one popover should appear, since the other triggers aren't hovered anymore.
There are no `close()` events being fired for the additional popovers.

I noticed that after removing the padding for `<my-trigger>` the issue disappears.

Maybe I'm doing something wrong?

**Comment by joejordanbrown** [comment]
Thank you for reporting this issue.

I've tested this locally on the library demo app and I can verify that I see the problem. I will need to check to make sure that when I moved the files to the library I haven't missed anything. I know this wasn't a problem in the initial prototype I created here https://material-extended-dashboard.firebaseapp.com/popover.

**Comment by joejordanbrown** [comment]
This issue has now been fixed, thank you for reporting this bug.

**Comment by kdudzik** [comment]
Thanks a lot for fixing this issue! Unfortunately, I'm not able to test it because of another issue, I'll report it separately.

**Comment by kdudzik** [comment]
I've just checked the new version and the bug is **almost** fixed. Sometimes still two popovers appear (previously there were many more). Tomorrow I'll try to prepare a minimal case.
