### ISSUE TITLE
Some Material Components are rendered wrong in Popover

### ISSUE THREAD

**Issue by merschel** [material-extended/mde#20]
#### Bug, feature request, or proposal:

Bug

#### What is the expected behaviour?

![bildschirmfoto 2018-01-12 um 11 01 00](https://user-images.githubusercontent.com/28409176/34869670-eac42ebe-f787-11e7-8914-8bd300af1865.png)

#### What is the current behaviour?

If I use Material stepper or expansion-panal than it is rendered wrong. The elements are closed but shown as open.  

![bildschirmfoto 2018-01-12 um 10 48 42](https://user-images.githubusercontent.com/28409176/34869673-ee614d86-f787-11e7-9b17-9e56f0cc05bc.png)

#### What are the steps to reproduce?

https://github.com/merschel/Material-Popover-Bug

#### What is the use-case or motivation for changing an existing behaviour?

-

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?

"devDependencies": {
    "@angular/animations": "^5.0.2",
    "@angular/cdk": "^5.0.0-rc.1",
    "@angular/cli": "1.5.2",
    "@angular/common": "^5.0.2",
    "@angular/compiler": "^5.0.2",
    "@angular/compiler-cli": "^5.0.2",
    "@angular/core": "^5.0.2",
    "@angular/forms": "^5.0.2",
    "@angular/language-service": "^5.0.2",
    "@angular/material": "^5.0.0-rc.1",
    "@angular/platform-browser": "^5.0.2",
    "@angular/platform-browser-dynamic": "^5.0.2",
    "@angular/router": "^5.0.2",
    "@material-extended/mde": "^1.0.0-alpha.6",
    "@types/glob": "^5.0.33",
    "@types/jasmine": "2.5.45",
    "@types/node": "~7.0.48",
    "@types/serialport": "^4.0.9",
    "chokidar": "^1.7.0",
    "codelyzer": "~4.0.1",
    "core-js": "^2.4.1",
    "electron": "1.8.2-beta.3",
    "electron-builder": "~19.45.5",
    "electron-reload": "^1.2.1",
    "hammerjs": "^2.0.8",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "jspdf": "^1.3.5",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "moment": "^2.19.2",
    "protractor": "~5.2.0",
    "rxjs": "^5.5.2",
    "ts-md5": "^1.2.2",
    "ts-node": "~3.3.0",
    "tslint": "~5.8.0",
    "typescript": "~2.4.2",
    "zone.js": "^0.8.4"

#### Other Comments

-

**Comment by joejordanbrown** [comment]
@merschel 

Thank you for reporting this issue.

Looking into this I don't think this is an issue/bug with this component but rather the `mat-accordion` component, when the popover component injects the popover and it's children, `mat-expansion-panel-header` should have `style="height: 48px;"` but this is missing, that's why you are seeing the UI problem. You can see the issue and information regarding it on the https://github.com/angular/material2/issues/5269.
