### ISSUE TITLE
Error with AOT Build

### ISSUE THREAD

**Issue by stocksr** [material-extended/mde#21]
#### Bug, feature request, or proposal:
if I enable the property fullTemplateTypeCheck as recommended by https://angular.io/guide/aot-compiler#fulltemplatetypecheck

I receive the following error:

`ERROR in node_modules\@material-extended\mde\mde.d.ts.MdePopover.html(1,105): : Property '_classList' is private and only accessible within class 'MdePopover'.`

#### What is the expected behaviour?
no error

#### What is the current behaviour?
build fails

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?
     "@angular/compiler": "^5.2.5",
     "@material-extended/mde": "^1.0.0-alpha.6",

**Comment by joejordanbrown** [comment]
@stocksr 

Thank you for reporting this issue.

I'll push a fix to resolve this issue today.

**Comment by stocksr** [comment]
Many thanks - tested with @material-extended/mde@1.0.0-alpha.10 and it is working correctly

**Comment by joejordanbrown** [comment]
@stocksr 

Great! Thank you for the update.
