### ISSUE TITLE
Bug! Dones't work

### ISSUE THREAD

**Issue by badwei** [material-extended/mde#22]
angular-version:5.2.6
angular-cdk version:5.2.4

ERROR 
TypeError
columnNumber: 9
fileName: "http://localhost:3000/main.bundle.js line 95 > eval"
lineNumber: 1136
message: "this._connectedTo is undefined"
ngDebugContext: Object { view: {…}, nodeIndex: 34, nodeDef: {…}, … }
ngErrorLogger: function bound ()
stack: "ConnectedPositionStrategy@webpack-internal:///./node_modules/@angular/cdk/esm5/overlay.es5.js:1136:9\nOverlayPositionBuilder.prototype.connectedTo@webpack-internal:///./node_modules/@angular/cdk/esm5/overlay.es5.js:2036:16\nMdePopoverTrigger.prototype._getPosition@webpack-internal:///./src/lib/popover/popover-trigger.ts:314:41\nMdePopoverTrigger.prototype._getOverlayConfig@webpack-internal:///./src/lib/popover/popover-trigger.ts:238:41\nMdePopoverTrigger.prototype._createOverlay@webpack-internal:///./src/lib/popover/popover-trigger.ts:224:26\nMdePopoverTrigger.prototype.openPopover@webpack-internal:///./src/lib/popover/popover-trigger.ts:126:13\nMdePopoverTrigger.prototype.togglePopover@webpack-internal:///./src/lib/popover/popover-trigger.ts:120:58\nMdePopoverTrigger.prototype.onClick@webpack-internal:///./src/lib/popover/popover-trigger.ts:87:13\nView_AppComponent_0/<@ng:///AppModule/AppComponent.ngfactory.js:74:27\nhandleEvent@webpack-internal:///./node_modules/@angular/core/esm5/core.js:13763:115\ncallWithDebugContext@webpack-internal:///./node_modules/@angular/core/esm5/core.js:15272:39\ndebugHandleEvent@webpack-internal:///./node_modules/@angular/core/esm5/core.js:14859:12\ndispatchEvent@webpack-internal:///./node_modules/@angular/core/esm5/core.js:10178:16\nrenderEventHandlerClosure/<@webpack-internal:///./node_modules/@angular/core/esm5/core.js:10803:38\ndecoratePreventDefault/<@webpack-internal:///./node_modules/@angular/platform-browser/esm5/platform-browser.js:2680:53\nZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:421:17\nonInvokeTask@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:24\nZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:420:17\nZone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:188:28\nZoneTask.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:496:24\ninvokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:1517:9\nglobalZoneAwareCallback@webpack-internal:///./node_modules/zone.js/dist/zone.js:1543:17\n"

ERROR CONTEXT 
{…}
elDef: Object { nodeIndex: 34, bindingIndex: 3, outputIndex: 2, … }
elView: Object { def: {…}, parent: {…}, state: 1036, … }
nodeDef: Object { nodeIndex: 34, bindingIndex: 3, outputIndex: 2, … }
nodeIndex: 34
view: Object { def: {…}, parent: {…}, state: 1036, … }
__proto__: Object { elOrCompView: Getter, injector: Getter, component: Getter, … }

**Comment by joejordanbrown** [comment]
@badwei 

Thank you for reporting this issue.

Please follow the issue template and submit a repo when possible.

I've tested this with the versions you stated and it works fine on StackBlitz see here https://stackblitz.com/edit/mde-popover

If you could provide a repo that has this error I'll be happy to help.

**Comment by badwei** [comment]
Thank you for your help. I think I have found out why the error occurred. this error occurred when I set the [mdePopoverTargetAt] attribute to refer to a div. But when the target div object changes to mat-toolbar, this error no longer occurs.  I tried to debug the source code, but did not get any useful solution to the problem. Finally I don't set [mdePopoverTargetAt] to fixed this error.

**Comment by joejordanbrown** [comment]
@badwei 

I'm glad you managed to work it out in the end.

The reason that you can't target a native element div is that it's not an Angular component so it doesn't expose the ElementRef. I created a directive to fix this `mdePopoverTarget`, you can see the example here https://github.com/material-extended/mde/blob/master/src/lib/popover/popover.md#popover-position-target-native-element-with-directive

You don't require that on any angular component that exposes the ElementRef.
