### ISSUE TITLE
Bug: Focus issue in popovers attached to input fields 

### ISSUE THREAD

**Issue by jetabekteshi** [material-extended/mde#229]
#### Bug, feature request, or proposal:
Using popovers in multiple input fields is causing a weird behaviour.

#### What is the expected behaviour?
The popovers don't mess up with the focus of the inputs.

#### What is the current behaviour?
Sometimes when I click on an input to write something it loses focus and the focus is moved to another input so the text ends up in the wrong field.

#### What are the steps to reproduce?
Try filling the inputs a couple of times and see that sometimes the focus switches back.

https://stackblitz.com/edit/mde-popover-zj65u6?file=app%2Fapp.component.html

Provide a working example using StackBlitz (or similar) to reproduce the problem.
StackBlitz Template: https://stackblitz.com/fork/mde-popover

**Comment by joejordanbrown** [comment]
@jetabekteshi 

Thanks for reporting the issue.

My guess is that it relates to this section of code https://github.com/joejordanbrown/popover/blob/39aa6f52e7d6d486dd6d7eabdb052472f2688306/projects/material-extended/mde/src/lib/popover/popover-trigger.ts#L277-L279 when the popover is closed it calls `_resetPopover()`. A quick workaround would be to add an option to disable this focus feature. https://github.com/joejordanbrown/popover/blob/39aa6f52e7d6d486dd6d7eabdb052472f2688306/projects/material-extended/mde/src/lib/popover/popover-trigger.ts#L333-L342

Let me know what you think.

**Comment by jetabekteshi** [comment]
Thank you for your fast response!

Haven't had the time to test this but the fix sounds good.

**Comment by jetabekteshi** [comment]
@joejordanbrown I tried this fix but seems like that's not the issue because it's behaving the same as before
