### ISSUE TITLE
Bug: Material expansion panels are opened inside popover

### ISSUE THREAD

**Issue by Szayet** [material-extended/mde#23]
#### Bug, feature request, or proposal:

As the title suggests, inside a popover window the expansion panels are opened by default, even though angular thinks they are closed.

#### What is the expected behaviour?

The panels should be left alone, so their respective expanded input would decide their visibility state.

#### What is the current behaviour?

They are opened by default. User has to close it first by hand to kick the expansion panel to the correct states.

#### What are the steps to reproduce?

StackBlitz Template: https://stackblitz.com/edit/mde-popover-bupa3s

**Comment by joejordanbrown** [comment]
@Szayet 

Thank you for reporting this issue.

This is a known bug with the Material Expansion Panels. You can see a previous issue that was created regarding this issue with the popover here #20.

For more details and a temporary fix, you can follow this material issue https://github.com/angular/material2/issues/5269
