### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by skrtheboss** [material-extended/mde#24]
#### Bug, feature request, or proposal:
Upgrade dependencies to support NG6

#### What is the expected behaviour?
Should support angular 6

#### What is the current behaviour?
It does not support angular  6

#### What are the steps to reproduce?
- NG6 app with @material-extended/mde

#### What is the use-case or motivation for changing an existing behaviour?
Angular 6 has been released

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?
Angular 6

**Comment by tosehee75** [comment]
bump

**Comment by joejordanbrown** [comment]
@skrtheboss @tosehee75

Thanks for the reporting this issue.

If you tag/ping me directly in future I'll see the notifications sooner.

You're welcome to create pull requests with the required Angular 6 changes. I'll get this updated and I should have it published today.

**Comment by eyalhakim** [comment]
@joejordanbrown Hi, i see that you made the changes, but didn't publish to npm yet?

**Comment by sdornan** [comment]
Looking forward to this update!

**Comment by tosehee75** [comment]
same here. Looking forward to it.

**Comment by joejordanbrown** [comment]
@skrtheboss @tosehee75 @eyalhakim @sdornan 

Great news the [@material-extended/mde](https://www.npmjs.com/package/@material-extended/mde) package has been released to npm.

**Comment by skrtheboss** [comment]
@joejordanbrown 

Looks awesome, but you forgot to put the `@angular/animations` in your peer dependencies, or am I wrong?

**Comment by tosehee75** [comment]
Cannot find module '@material-extended/mde/popover

I get this error with latest mde 2.0.0

**Comment by tosehee75** [comment]
import {MdePopover} from "@material-extended/mde/lib/popover";

Does it change to above?

**Comment by skrtheboss** [comment]
@tosehee75 

Why are you doing deep import of the MdePopover component? Just import it like so `import {MdePopover} from "@material-extended/mde";`.

**Comment by skrtheboss** [comment]
@tosehee75 

I've done a  [StackBlitz here](https://stackblitz.com/edit/mde-popover-skvvx2?file=app%2Fapp.component.ts).

Don't know what you are doing wrong, but to me is seems to be working perfectly.

**Comment by tosehee75** [comment]
Thanks.

I must have missed it somehow.. Thanks again.

**Comment by joejordanbrown** [comment]
@skrtheboss 

Yes, that's correct `@angular/animations` should have been a peer dependency. It's now amended.
