### ISSUE TITLE
Error when using fullTemplateTypeCheck

### ISSUE THREAD

**Issue by stocksr** [material-extended/mde#25]
#### Bug
When using fullTemplateTypeCheck in the AOT compiler I get the following error message
```Directive MdePopoverTrigger, Expected 1 arguments, but got 0.```

#### What is the expected behaviour?
No Error 

#### What are the steps to reproduce?
Attempt to build with AOT and ```"angularCompilerOptions": {"fullTemplateTypeCheck": true}```

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?
angular  6.0.2
material-extended 2.0.0
Typescript 2.7
Windows 10

#### Other Comments
see also https://github.com/angular/angular/issues/21329

**Comment by joejordanbrown** [comment]
@stocksr 

Thanks for reporting this issue.

I will look into this shortly and hopefully push a fix soon.

**Comment by skrtheboss** [comment]
Any updates on this issue?

**Comment by ester969** [comment]
i got error when ckick mdepopover in angular 5 : this._overlay.position(...).flexibleConnectedTo is not a function
please help !!
