### ISSUE TITLE
button click event inside the the popover content

### ISSUE THREAD

**Issue by varunprakas** [material-extended/mde#31]
I have a small form with 'cancel' and 'submit' button inside the popover. i am trying to close the popover after user submit the form. i tried many ways which is explained in the popover. unfortunately it didn't work. is there any work around on this scenario?

**TS file**

```
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  flag = false
  cancelPopover(e){
    this.flag = true
  }
}
```

**Html file**

```
<div class="container">
  <button mat-raised-button color="primary"
    [mdePopoverTriggerFor]="appPopover" mdePopoverTriggerOn="click" [mdePopoverCloseOnClick]="flag">
    Show Popover
  </button>
  <mde-popover #appPopover="mdePopover">
    <mat-card style="max-width: 300px">
      <mat-card-content>
      A material design popover component
      </mat-card-content>
      <button (click)="cancelPopover($event)">Cancel</button>
    </mat-card>
  </mde-popover>
</div>
```

**Comment by varunprakas** [comment]
TS file
`
import { Component } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ]
})
export class AppComponent  {
  name = 'Angular 6';
  flag = false
  cancelPopover(e){
    this.flag = true
  }
}
`
Html file

`<mat-toolbar color="primary">
  <h1>Angular Material Popover Example</h1>
</mat-toolbar> 


<div class="container">

  <p>
    A material design popover component created using Angular version 6 with the Angular CDK.
  </p>

  <button mat-raised-button color="primary"
    [mdePopoverTriggerFor]="appPopover" mdePopoverTriggerOn="click" [mdePopoverCloseOnClick]="flag">
    Show Popover
  </button>

  <mde-popover #appPopover="mdePopover">
    <mat-card style="max-width: 300px">
      <mat-card-content>
      A material design popover component created using Angular version 6 with the Angular CDK.
      </mat-card-content>
      <button (click)="cancelPopover($event)">Cancel</button>
    </mat-card>
  </mde-popover>

</div>
`

**Comment by joejordanbrown** [comment]
@varunprakas 

Yes that's possible, please see this example here that I've created https://stackblitz.com/edit/mde-popover-example-toggling-the-popover-programmatically

**Comment by varunprakas** [comment]
Thanks Joe for the help,

I am using this popover in multiple times in a loop. when i try to use the multiple popover . when we click on the first button the popover working perfectly with close button but when we click on the second button both popover window appeared in the view. i am mentioning the code below

```
<button mat-raised-button color="primary"
    [mdePopoverTriggerFor]="appPopover1"
    mdePopoverTriggerOn="click">
    Show Popover 1
  </button>

 <button mat-raised-button color="primary"
    [mdePopoverTriggerFor]="appPopover2"
    mdePopoverTriggerOn="click">
    Show Popover 2
  </button>
  <mde-popover #appPopover1="mdePopover" [mdePopoverOverlapTrigger]="false" [mdePopoverCloseOnClick]="false">
    <mat-card style="max-width: 300px">
      <mat-card-content>
      A material design popover 1 component created using Angular version 6 with the Angular CDK.
      </mat-card-content>
      <mat-card-actions align="right">
        <button (click)="closePopover()" mat-button>Close</button>

        <button (click)="onSubmit()" mat-button>Submit</button>
      </mat-card-actions>
    </mat-card>
  </mde-popover>
  <mde-popover #appPopover2="mdePopover" [mdePopoverOverlapTrigger]="false" [mdePopoverCloseOnClick]="false">
    <mat-card style="max-width: 300px">
      <mat-card-content>
      A material design popover 2 component created using Angular version 6 with the Angular CDK.
      </mat-card-content>
      <mat-card-actions align="right">
        <button (click)="closePopover()" mat-button>Close</button>

        <button (click)="onSubmit()" mat-button>Submit</button>
      </mat-card-actions>
    </mat-card>
  </mde-popover>```

**Comment by joejordanbrown** [comment]
@varunprakas 

You will need to use `@ViewChildren(MdePopoverTrigger) trigger: QueryList<MdePopoverTrigger>;`, see example here https://stackblitz.com/edit/mde-popover-example-multi-toggling-the-popover-programmatically

**Comment by joejordanbrown** [comment]
@varunprakas 

That's due to `_results` being private, you will need to use `toArray()` like this `this.trigger.toArray()[id].togglePopover();` for it to work correctly.

I've updated the example to use `toArray()` https://stackblitz.com/edit/mde-popover-example-multi-toggling-the-popover-programmatically

**Comment by varunprakas** [comment]
Thanks you so much for your support and help :)

**Comment by varunprakas** [comment]
Hi Joe,

I am using `Angular 5.0` and `@material-extended/mde": "1.0.0-alpha.6`
Wether the above solution will work or not. if not let me know the solution please

Thanks
Varun

**Comment by pritibaheticompumatrice** [comment]
When I try to close popover on clicking on cancel button it doesn' close it on first click. I need to again click on the cancel button and it closes the popover. I m using multiple popovers.
Following is the code for closing pop-over:
`closePopover(id:number){
this.trigger.toArray()[id].togglePopover();
}`

**Comment by joejordanbrown** [comment]
@pritibaheticompumatrice 

Please create a demo of your issue on stackblitz.com, I will then be able to assist.

**Comment by sameerthekhans** [comment]
@joejordanbrown [As you said](https://github.com/material-extended/popover/issues/31#issuecomment-409125829), What if i have nested ngfor [see example](https://stackblitz.com/edit/mde-popover-9twqbf?file=app/app.component.html) - Currently I am using foreach and checking which popover is opened and then closing it

**Comment by pritibaheticompumatrice** [comment]
@joejordanbrown My issue is solved. It was occurring because of other bug from my code. I was using stop propagation so it was not letting me close the popover on the first click as it stops every action.  I found a workaround for it. Now your code is working fine for me.
Thanks.

**Comment by janwez** [comment]
Can we do it for <a href=" " (click)="method"> read more</a>anchor  instead of using button as I am trying but the click event is not working and I get any error in console i have also kept debugger but click method is not getting called inside a popover div tag
