### ISSUE TITLE
button click event inside the the popover content is not working in `angular 5.0` and `@material-extended/mde": "1.0.0-alpha.6`

### ISSUE THREAD

**Issue by varunprakas** [material-extended/mde#33]
Hi Joe,

The issue related to the below thread which we already discussed 
https://github.com/material-extended/mde/issues/31

I am using `Angular 5.0` and `@material-extended/mde": "1.0.0-alpha.6`
Wether the above solution will work or not. if not let me know the solution please

Thanks
Varun

**Comment by joejordanbrown** [comment]
@varunprakas 

Please create a demo with how you have your angular component set out using https://stackblitz.com/edit/mde-popover-example-multi-toggling-the-popover-programmatically you can fork that and edit the library versions that are imported on the left to what you currently use, I will then be able to see the issue you are facing.
