### ISSUE TITLE
Feature: Add an option to disallow popover from closing when clicked outside of its body

### ISSUE THREAD

**Issue by shuhkla** [material-extended/mde#36]
#### Bug, feature request, or proposal:

Feature Request

#### What is the expected behaviour?

Have the popover stay opened when the user clicks outside of popover body

#### What is the current behaviour?

Popover will close when the user clicks anywhere on the page outside the popover.

#### What are the steps to reproduce?

This is reproducible on the demo page:
https://uixd.co.uk/open-source-software/material-extended/demo/

#### What is the use-case or motivation for changing an existing behaviour?

mdePopoverCloseOnClick input directive allows popover to stay open when the user clicks inside the popover body. A similar option should be given to have the popover persist to prevent the popover from closing when the user clicks anywhere else. This is especially important when the popover can contain complex forms / buttons etc. to which the users must interact with.

**Comment by joejordanbrown** [comment]
@shuhkla 

This feature has just landed in the master, it will require `[mdePopoverBackdropCloseOnClick]="false"` to be set on the trigger element.
