### ISSUE TITLE
Please update peerDependencies for angular 7

### ISSUE THREAD

**Issue by harryy2510** [material-extended/mde#37]
Please update peerDependencies for angular 7

**Comment by joejordanbrown** [comment]
@harryy2510 

Sorry about the delay, I should state somewhere that when creating issues you should ping me directly with @joejordanbrown to be sure i receive the notification promptly.

I started this when v7 was released but haven't had time to test just yet; I'll find some time this week, you're open to creating a pull request though.

**Comment by harryy2510** [comment]
#38

**Comment by kostia-lev** [comment]
@joejordanbrown please check the pull request

**Comment by harryy2510** [comment]
@joejordanbrown Please check now!

**Comment by kostia-lev** [comment]
removed this plugin from my project, it seems to be not supported anymore

**Comment by scharnyw** [comment]
> 
> 
> removed this plugin from my project, it seems to be not supported anymore

For now you can just use a local copy and modify the peer dependencies instead of using npm. Don't think any code change is needed to work with Angular 7. I'm sure the author will get around to updating it soon enough.

**Comment by joejordanbrown** [comment]
@harryy2510 @kostia-lev @scharnyw @Plondrein

Sorry for the delay, I've been to busy with work lately.
