### ISSUE TITLE
Could not resolve './popover-module' from dist/material-extended/mde/esm2015/public-api.js

### ISSUE THREAD

**Issue by andypopa** [material-extended/mde#39]
#### Bug, feature request, or proposal:
Bug

#### What is the expected behaviour?
The library should compile when running npm run build:library

#### What is the current behaviour?
The library does not compile

`> @material-extended/mde@2.1.1 build:library /Users/andreipopa/skyborg-app/node_modules/@material-extended/mde
> ng build @material-extended/mde

Building Angular Package
Building entry point '@material-extended/mde'
Compiling TypeScript sources through ngc
Bundling to FESM2015

BUILD ERROR
Could not resolve './popover-module' from dist/material-extended/mde/esm2015/public-api.js
Error: Could not resolve './popover-module' from dist/material-extended/mde/esm2015/public-api.js
    at error (/Users/andreipopa/skyborg-app/node_modules/@material-extended/mde/node_modules/rollup/dist/rollup.js:3460:30)
    at /Users/andreipopa/skyborg-app/node_modules/@material-extended/mde/node_modules/rollup/dist/rollup.js:21850:25
    at <anonymous>

Could not resolve './popover-module' from dist/material-extended/mde/esm2015/public-api.js
Error: Could not resolve './popover-module' from dist/material-extended/mde/esm2015/public-api.js
    at error (/Users/andreipopa/skyborg-app/node_modules/@material-extended/mde/node_modules/rollup/dist/rollup.js:3460:30)
    at /Users/andreipopa/skyborg-app/node_modules/@material-extended/mde/node_modules/rollup/dist/rollup.js:21850:25
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @material-extended/mde@2.1.1 build:library: `ng build @material-extended/mde`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @material-extended/mde@2.1.1 build:library script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?
`Angular CLI: 7.0.5
Node: 9.11.1
OS: darwin x64
Angular: 7.0.3
... animations, cdk, common, compiler, compiler-cli, core, forms
... http, language-service, material, platform-browser
... platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.10.5
@angular-devkit/build-angular      0.10.5
@angular-devkit/build-ng-packagr   0.10.5
@angular-devkit/build-optimizer    0.10.5
@angular-devkit/build-webpack      0.10.5
@angular-devkit/core               7.0.5
@angular-devkit/schematics         7.0.5
@angular/cli                       7.0.5
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.0.5
@schematics/angular                7.0.5
@schematics/update                 0.10.5
ng-packagr                         4.4.0
rxjs                               6.3.3
typescript                         3.1.6
webpack                            4.19.1`

#### Other Comments
Used @harry2510 fork, but the behavior appears on the main package as well. The package doesn't automatically compile when installing either because of this problem.

**Comment by joejordanbrown** [comment]
@andypopa 

I didn't have this issue when testing that fork. I've released the Angular 7 version now. 

Let me know if you have any issues with the new package.
