### ISSUE TITLE
when switching between popover fields, sometimes previous shows up again

### ISSUE THREAD

**Issue by Plondrein** [material-extended/mde#4]
plunker copied from previous issue (1k ms delay), just changed version to latest.

http://plnkr.co/edit/8iQPE1DRSRGQjriGbjRm?p=preview

When mouse is hanging for a while at one popover-having div, after going directly to the other, previous popover shows as well as new one ( previous one hides but instantly appears again). It doesn't happen always.

**Comment by joejordanbrown** [comment]
Thank you for reporting this issue.

I have fixed this bug now and just published the fix to NPM, please let me know if you have any more problems.
