### ISSUE TITLE
Access Mde Popover component form an other component

### ISSUE THREAD

**Issue by tirupati07** [material-extended/mde#43]
#### feature request, or proposal:
How to access the mde-popover with button template reference outside the component?

#### What is the expected behaviour?
 <button mat-raised-button color="primary"
  [mdePopoverTriggerFor]="appPopover"
  mdePopoverTriggerOn="click">
  Show Popover
</button>

#### What is the current behaviour?
I was trying to call [mdePopoverTriggerFor] form a custom button I have in a card component.
But, It is giving me an error message saying #appPopover reference must be inside the popover component I am creating. Is there any way to seperate "button" used to trigger the popover from outside the template of popover component. 
My popover shouldn't have button inside the component. If so, there is a tight coupling between button and mde popover. 
#### What are the steps to reproduce?

Provide a working example using StackBlitz (or similar) to reproduce the problem.
StackBlitz Template: https://stackblitz.com/fork/mde-popover

**Comment by joejordanbrown** [comment]
@tirupati07 

Sorry about the slow reply.

Could you provide an example on StackBlitz how your components are set up? This will help me see exactly how we could overcome your issue.

You can use https://stackblitz.com/fork/mde-popover to create an example.

I'm wondering if having the popover component in its own component just how the Material Dialog works could fix your issue. You can see the examples for the Dialog here https://material.angular.io/components/dialog/examples. If it could please create a feature request for this and we will look at the possibility for this in a future release.
