### ISSUE TITLE
Resizable Popup

### ISSUE THREAD

**Issue by tirupati07** [material-extended/mde#47]
#### Bug, feature request, or proposal:
Resize the popup window once it is opened.

#### What is the current behaviour?
No way we can resize the window as of now.

#### What are the steps to reproduce?

Provide a working example using StackBlitz (or similar) to reproduce the problem.
StackBlitz Template: https://stackblitz.com/fork/mde-popover

**Comment by joejordanbrown** [comment]
@tirupati07 

The size of the popover is set by the containing element. 

Can you provide further details or show an example of the issue in question?
