### ISSUE TITLE
Unable to use the component with Angular 12

### ISSUE THREAD

**Issue by vicpeters** [material-extended/mde#473]
#### Bug, feature request, or proposal:
Unable to add the component. Installation failed due to peers conflict.

#### What is the current behaviour?
Found: @angular/animations@12.0.1
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^12.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^8.0.0 || ^9.0.0-0" from @material-extended/mde@3.0.3
npm ERR! node_modules/@material-extended/mde
npm ERR!   @material-extended/mde@"*" from the root project

#### What are the steps to reproduce?
npm install @material-extended/mde

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?
Angular 12.0.1 TypeScript ~4.2.3

**Comment by Plondrein** [comment]
Have you tried --force flag?
