### ISSUE TITLE
Popover flickering with large contents

### ISSUE THREAD

**Issue by anishcp** [material-extended/mde#49]
#### Bug, feature request, or proposal:
The popover is flickering with large text contents.

#### What are the steps to reproduce?

https://stackblitz.com/edit/mde-popover-ugqcfs

**Comment by joejordanbrown** [comment]
@anishcp 

That's sometimes an issue when using hover to trigger, increasing the default leave delay `mdePopoverLeaveDelay` should resolve that issue.

```html
<button mat-raised-button color="primary" [mdePopoverTriggerFor]="appPopover" mdePopoverTriggerOn="hover" #popoverTrigger="mdePopoverTrigger">
  Show Popover
</button>

<mde-popover #appPopover="mdePopover" [mdePopoverOverlapTrigger]="false" mdePopoverLeaveDelay="1000">
...
</mde-popover>
```

https://stackblitz.com/edit/mde-popover-vdwkgn?file=app/app.component.html

Let me know if you're still having an issue.

**Comment by kdatar1604** [comment]
Hello @joejordanbrown : I am facing this flickering issue and I tried it in above example share it flickers when focus is at border
