### ISSUE TITLE
Is it compatible with Angular 2 version 14

### ISSUE THREAD

**Issue by agdev** [material-extended/mde#890]
When installing for angular 14 getting error
 WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: upgrade-to-14@0.0.0
npm ERR! Found: @angular/animations@14.2.11
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"^14.2.11" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^8.0.0 || ^9.0.0-0" from @material-extended/mde@3.0.3
npm ERR! node_modules/@material-extended/mde
npm ERR!   @material-extended/mde@"*" from the root project

Is it compatible with Angular 2 version 14?

**Comment by maccaroo** [comment]
I get the same issue.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: my-app@0.0.0
npm ERR! Found: @angular/animations@13.3.12
npm ERR! node_modules/@angular/animations
npm ERR!   @angular/animations@"~13.3.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/animations@"^8.0.0 || ^9.0.0-0" from @material-extended/mde@3.0.3
npm ERR! node_modules/@material-extended/mde
npm ERR!   @material-extended/mde@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
