### ISSUE TITLE
Attempting to attach an unknown Portal type. BasePortalHost accepts either a ComponentPortal or a TemplatePortal.

### ISSUE THREAD

**Issue by eyalhakim** [material-extended/mde#9]
Occurs when trying to open a popover when code is compiled in production mode

**Comment by joejordanbrown** [comment]
@eyalhakim 

Thanks for reporting this, I know there were problems with this before and I fixed them in the build system. It must have come back due to changing over to the CDK, I'll investigate now.

**Comment by eyalhakim** [comment]
@joejordanbrown thank you very much!

**Comment by joejordanbrown** [comment]
@eyalhakim this should now be fixed. Please let me know if that problem has been resolved so I can close this issue.

**Comment by eyalhakim** [comment]
@joejordanbrown resolved indeed! thank you

**Comment by realshadow** [comment]
@joejordanbrown I have the same problem, sadly I am stuck at version 1.0.0-alpha.0 due to project dependencies. Any idea how can I fix this issue? I can not find the relevant commit in history
