### ISSUE TITLE
Please update dependencies to be compatible with latest Angular

### ISSUE THREAD

**Issue by developer707** [material-extended/mde#918]
#### What is the expected behaviour?
Should be able to run npm install without conflicting peer dependencies

#### What is the current behaviour?
Confilcting peer-dependecy @angular/cdk@10.2.7

#### What are the steps to reproduce?

using Angular 14 this library is not compatble with cdk, andimations, material, 

#### What is the use-case or motivation for changing an existing behaviour?
to keep library up to date with Angular Upgrades.

#### Which versions of Angular, Material-Extended, OS, TypeScript, browsers are affected?
Angular 14

**Comment by dechamps** [comment]
Not stale - the library still isn't compatible with modern Angular.

**Comment by developer707** [comment]
@joejordanbrown Are you able to update this library?
